services:
  prestashop:
    image: prestashop/prestashop-flashlight:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - PS_DOMAIN=localhost:8000
      - CUSTOM_FOO=bar
      - CUSTOM_MUSH=room
    volumes:
      - ./init-scripts:/tmp/init-scripts
    ports:
      - 8000:80

  mysql:
    image: mariadb:lts
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--host=localhost",
          "--user=root",
          "--password=prestashop",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prestashop
